### ISSUE TITLE
能否增加python3版本

### ISSUE THREAD

**Issue by aieofwang** [purefkh/CQU_drcom#12]
新版本openwrt编译后无法找到python2的ipk安装包，opkg软件源也仅有python3

**Comment by Afcsee** [comment]
我也遇到了同样的问题，请问你是怎么解决的？🤔

**Comment by aieofwang** [comment]
> 我也遇到了同样的问题，请问你是怎么解决的？🤔

在系统-软件包-配置中修改发行版软件源，将openwrt_packages后的网址修改为您在openwrt软件源中找到的具有python2软件包的其他版本且与您的硬件架构相符的packages源
例如，我之前的packages源为https://mirrors.bfsu.edu.cn/openwrt/snapshots/packages/mipsel_24kc/packages/ ，将其修改为
https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/19.07.3/packages/mipsel_24kc/packages/ ，提交更改后，再刷新软件列表，就能在可用软件包里面找到python2了

**Comment by Afcsee** [comment]
> > 我也遇到了同样的问题，请问你是怎么解决的？🤔
> 
> 在系统-软件包-配置中修改发行版软件源，将openwrt_packages后的网址修改为您在openwrt软件源中找到的具有python2软件包的其他版本且与您的硬件架构相符的packages源
> 例如，我之前的packages源为https://mirrors.bfsu.edu.cn/openwrt/snapshots/packages/mipsel_24kc/packages/ ，将其修改为
> https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/19.07.3/packages/mipsel_24kc/packages/ ，提交更改后，再刷新软件列表，就能在可用软件包里面找到python2了

非常感谢

**Comment by weearc** [comment]
https://github.com/purefkh/CQU_drcom/releases/tag/2.2.4.2b
