### ISSUE TITLE
重大校园网A区安装出错

### ISSUE THREAD

**Issue by wan-yahui** [purefkh/CQU_drcom#13]
![image](https://user-images.githubusercontent.com/49581114/92256663-8fd27c80-ef06-11ea-87db-631c2137f717.png)
这个该怎么办呀？而且在init_d中没有drcomctl进程。

**Comment by purefkh** [comment]
commit fe29b77a6ea775d1cee73923a3d23cc7ddc26aa5 中已修复可能出现的 `init_d中没有drcomctl进程` 的问题，可以`git clone https://github.com/purefkh/CQU_drcom.git` 使用最新修复版，我们将在几次commit内发布新的Stable Release。
目前产生 `mv： can't rename 'latest-wired.py': No such file or directory` 的原因仍在排查，我们测试过几次没有复现。

**Comment by purefkh** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/49581114/92256663-8fd27c80-ef06-11ea-87db-631c2137f717.png)
> 这个该怎么办呀？而且在init_d中没有drcomctl进程。

commit fe29b77a6ea775d1cee73923a3d23cc7ddc26aa5 中已修复可能出现的 `init_d中没有drcomctl进程` 的问题，可以`git clone https://github.com/purefkh/CQU_drcom.git` 使用最新修复版，我们将在几次commit内发布新的Stable Release。
目前产生 `mv： can't rename 'latest-wired.py': No such file or directory` 的原因仍在排查，我们测试过几次没有复现。

**Comment by Hagb** [comment]
`mv： can't rename 'latest-wired.py': No such file or directory` 看起来是由于执行命令的路径中没有`latest-wired.py`文件。
出现这个问题时具体是怎么操作的？

**Comment by weearc** [comment]
fixed in pre-release v2.2.4
