### ISSUE TITLE
A区安装中出错

### ISSUE THREAD

**Issue by Afcsee** [purefkh/CQU_drcom#15]
![QQ图片20200910112322.png](https://i.loli.net/2020/09/10/cfYerhJG6ETVAK2.png)
我已经连好内网了，但是这里Network checking还是失败了，请问应该怎么处理呢

**Comment by purefkh** [comment]
> ![QQ图片20200910112322.png](https://i.loli.net/2020/09/10/cfYerhJG6ETVAK2.png)
> 我已经连好内网了，但是这里Network checking还是失败了，请问应该怎么处理呢

如果前面的步骤都没有出错，那安装很有可能是成功了的。当前安装完成后的网络连通性检测存在一些问题，检测时可能正处在拨号过程中。

**Comment by Afcsee** [comment]
> > ![QQ图片20200910112322.png](https://camo.githubusercontent.com/647174e03122734d122f5db42e7c384524ad1d46/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30392f31302f6366596572684a4736455456414b322e706e67)
> > 我已经连好内网了，但是这里Network checking还是失败了，请问应该怎么处理呢
> 
> 如果前面的步骤都没有出错，那安装很有可能是成功了的。当前安装完成后的网络连通性检测存在一些问题，检测时可能正处在拨号过程中。

噢，感谢解答，那么请问一下我现在应该怎么处理呢？
