### ISSUE TITLE
当前的 Release 已过时

### ISSUE THREAD

**Issue by LittleModesty** [purefkh/CQU_drcom#28]
目前的 Release 已经因为网络更新在D区无法使用，建议重新发布一个 Release ，或者更改 Readme 为直接下载 master 分支的代码来安装。

**Comment by weearc** [comment]
由于本人未在虎溪校区因此没能进行配置包更改。如急需使用望提供目前可用该校区的配置信息，以便我们也进行更改。未来也会考虑以补丁形式进行更新提供。

**Comment by LittleModesty** [comment]
master分支的代码目前是可以使用的。但是 Readme 中的使用事项部分会引导用户下载 Release 中的安装包，而最新的 Release 创建于去年九月，没有合并后面虎溪网络更新后的代码。

**Comment by weearc** [comment]
已发新 Release https://github.com/purefkh/CQU_drcom/releases/tag/2.2.4.2b
