### ISSUE TITLE
A区配置失败，换源步骤报错

### ISSUE THREAD

**Issue by MiaoNan** [purefkh/CQU_drcom#37]
感谢大佬提供的脚本！我直接使用脚本安装失败，手动分解脚本执行，直到在执行安装python步骤时，出现以下错误：
![$9{}B%PFU%F437K4 DIJR$P](https://user-images.githubusercontent.com/11154392/142831457-da885e21-6f50-4dc5-a04a-fbbb1048ee92.jpg)
换源至CQU源过程中出现报错，无论是否连接到外网，都是以上报错。另外尝试清华源也有以下报错
于是Google了一下，有帖子说可能是DNS问题，但通过ping外网域名发现DNS并没有问题，如下所示：
![9 NI1C(1KN@Z6BLL9K{ZPWY](https://user-images.githubusercontent.com/11154392/142831623-8680a5aa-b393-4ad7-9be5-36b499273237.jpg)
而在尝试更换为官方源的时候，则可以正常更换，（但没有python）。
![_R}8CI82ZBN}7$I~F{2GS(X](https://user-images.githubusercontent.com/11154392/142832623-ff82e9fc-d560-4090-bb92-1a68720d85af.jpg)

采用MT7620A的路由器，系统版本：OpenWrt 21.02.0-rc3, r16172-2aba3e9784

多有打扰，烦请大佬出手相助

**Comment by weearc** [comment]
请将脚本中https字符串变更为http，即不通过ssl方式访问镜像并再次尝试是否正常工作。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月22日(周一) 下午5:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CQU-drcom/CQU_drcom] A区配置失败，换源步骤报错 (Issue #37)




 
感谢大佬提供的脚本！我直接使用脚本安装失败，手动分解脚本执行，直到在执行安装python步骤时，出现以下错误：
 
 换源至CQU源过程中出现报错，无论是否连接到外网，都是以上报错。另外尝试清华源也有以下报错
 于是Google了一下，有帖子说可能是DNS问题，但通过ping外网域名发现DNS并没有问题，如下所示：
 
 而在尝试更换为官方源的时候，则可以正常更换，（但没有python）。
 
 
采用MT7620A的路由器，系统版本：OpenWrt 21.02.0-rc3, r16172-2aba3e9784
 
多有打扰，烦请大佬出手相助

**Comment by MiaoNan** [comment]
通过http方式换源问题已解决，谢谢大佬出手相助
