### ISSUE TITLE
运行的时候报错

### ISSUE THREAD

**Issue by Q7v3Qy** [purefkh/CQU_drcom#39]

**Comment by Q7v3Qy** [comment]
`Traceback (most recent call last):
  File "/usr/bin/drcom-python2", line 574, in <module>
    main()
  File "/usr/bin/drcom-python2", line 555, in main
    package_tail = login(username, password, server)
  File "/usr/bin/drcom-python2", line 411, in login
    salt = challenge(svr,time.time()+random.randint(0xF,0xFF))
  File "/usr/bin/drcom-python2", line 82, in challenge
    s.sendto("\x01\x02"+t+"\x09"+"\x00"*15, (svr, 61440))
socket.error: [Errno 101] Network is unreachable
Traceback (most recent call last):
  File "/usr/bin/drcom-python2", line 574, in <module>
    main()
  File "/usr/bin/drcom-python2", line 555, in main
    package_tail = login(username, password, server)
  File "/usr/bin/drcom-python2", line 411, in login
    salt = challenge(svr,time.time()+random.randint(0xF,0xFF))
  File "/usr/bin/drcom-python2", line 82, in challenge
    s.sendto("\x01\x02"+t+"\x09"+"\x00"*15, (svr, 61440))
socket.error: [Errno 101] Network is unreachable
`

**Comment by Hagb** [comment]
看起来你没有连上重大的内网，看一看 `ip route` 的输出？

**Comment by Q7v3Qy** [comment]
> 看起来你没有连上重大的内网，看一看 `ip route` 的输出？

现在没有问题了，另一个问题是我发现他半夜不用了好像会段网？还有个问题就是我今天和昨天有时候校园网没给我的路由器分配ip，是不是要把wan口的协议改成DCHP模式？

**Comment by weearc** [comment]
> > 看起来你没有连上重大的内网，看一看 `ip route` 的输出？
> 
> 现在没有问题了，另一个问题是我发现他半夜不用了好像会段网？还有个问题就是我今天和昨天有时候校园网没给我的路由器分配ip，是不是要把wan口的协议改成DCHP模式？

半夜断网的缘故是没有主动产生流量，配置脚本中网络检测模块即可

**Comment by Q7v3Qy** [comment]
> > > 看起来你没有连上重大的内网，看一看 `ip route` 的输出？
> > 
> > 
> > 现在没有问题了，另一个问题是我发现他半夜不用了好像会段网？还有个问题就是我今天和昨天有时候校园网没给我的路由器分配ip，是不是要把wan口的协议改成DCHP模式？
> 
> 半夜断网的缘故是没有主动产生流量，配置脚本中网络检测模块即可

另一个问题，这个脚本是不是自动把这个加入了启动项

**Comment by weearc** [comment]
> 另一个问题，这个脚本是不是自动把这个加入了启动项

@Q7v3Qy 显然是的，不过仍可以通过 web 控制台或终端手动关闭
