### ISSUE TITLE
python:Not Found

### ISSUE THREAD

**Issue by LiuZhipeng99** [purefkh/CQU_drcom#4]
![SharedScreensho2t](https://user-images.githubusercontent.com/44400198/64903868-9400fb00-d6f3-11e9-8b1b-93a70972c5f7.jpg)

**Comment by weearc** [comment]
请附带：脚本版本、路由器型号、固件名称及版本以便于我们一起查找问题所在


 
---Original---

**Comment by weearc** [comment]
看了下没找到99-drcom的问题，要求是把整个文件夹上传，似乎你是上传了脚本哦。以及你使用的分支是哪个。

**Comment by LiuZhipeng99** [comment]
使用的master，固件是openwrt-15.05-ramips-mt7620-hc5661，在上传文件夹后按md走的流程

**Comment by LiuZhipeng99** [comment]
另外那个路由器直接连内网就能下载吗

**Comment by weearc** [comment]
> 另外那个路由器直接连内网就能下载吗

对的。


> 使用的master，固件是openwrt-15.05-ramips-mt7620-hc5661，在上传文件夹后按md走的流程

从截图来看至少你的固件版本可能是14.07。那么你的路由器型号是什么呢？如果可以的话请刷入最新版本的固件。另外私有固件以及恩山论坛等地方的固件可能存在问题。

**Comment by LiuZhipeng99** [comment]
> > 另外那个路由器直接连内网就能下载吗
> 
> 对的。
> 
> > 使用的master，固件是openwrt-15.05-ramips-mt7620-hc5661，在上传文件夹后按md走的流程
> 
> 从截图来看至少你的固件版本可能是14.07。那么你的路由器型号是什么呢？如果可以的话请刷入最新版本的固件。另外私有固件以及恩山论坛等地方的固件可能存在问题。

升级了固件但是还是一样结果，看起来是python没有安装。也没有这个变量。这个固件来自http://rssn.cn/roms/这里。其他问题我也看不出来。
另外我就是下了压缩包将里面py的Is_test改为true就上传了，按照指示到如图这样

**Comment by LiuZhipeng99** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/44400198/64924043-cb19fe00-d812-11e9-9858-ecdd657ba820.jpg)

**Comment by LiuZhipeng99** [comment]
这个下载地址是在外网？

**Comment by weearc** [comment]
> 升级了固件但是还是一样结果，看起来是python没有安装。也没有这个变量。这个固件来自http://rssn.cn/roms/ 这里。其他问题我也看不出来
> 另外我就是下了压缩包将里面py的Is_test改为true就上传了，按照指示到如图这样

请从[该地址](https://openwrt.org/toh/hiwifi/hiwifi_gee_hc5661)下载 ***openwrt官方社区的固件*** 第三方极路由固件不能保证可用性。
至于如你图上展示明显没更改过源的痕迹，这与我们脚本中的操作不符。可认为是第三方固件导致的问题。如不希望继续尝试刷入可能需要手动在luci中更改软件源并安装python（请确保软件源项目数正确）我已检查过源的情况，其中包含包Python（openwrt15.05）。
如希望继续使用此脚本请确保刷入官方18.06版本的固件。

**Comment by weearc** [comment]
正常情况下应有如下输出：
```sh
root@OpenWrt:~# opkg update
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/targets/ramips/mt7620/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/targets/ramips/mt7620/packages/Packages.sig
Signature check passed.
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/targets/ramips/mt7620/kmods/4.14.131-1-f908844d5e5aab0a4b27f7d4c77655d0/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_kmods
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/targets/ramips/mt7620/kmods/4.14.131-1-f908844d5e5aab0a4b27f7d4c77655d0/Packages.sig
Signature check passed.
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/packages/mipsel_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/packages/mipsel_24kc/base/Packages.sig
Signature check passed.
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/packages/mipsel_24kc/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/packages/mipsel_24kc/luci/Packages.sig
Signature check passed.
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/packages/mipsel_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/packages/mipsel_24kc/packages/Packages.sig
Signature check passed.
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/packages/mipsel_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/packages/mipsel_24kc/routing/Packages.sig
Signature check passed.
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/packages/mipsel_24kc/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading http://mirrors.cqu.edu.cn/openwrt/releases/18.06.4/packages/mipsel_24kc/telephony/Packages.sig
Signature check passed.
```

**Comment by weearc** [comment]
请务必确保源条目包含如下条目：
- core
- kmods
- base
- luci
- packages
- routing
- telephony

**Comment by weearc** [comment]
> 这个下载地址是在外网？

并不，是内网并且在测试中断网条件下尝试成功。

**Comment by LiuZhipeng99** [comment]
非常感谢学长的耐心指导，已经在极路由HC5661上成功了。另外学长也是在虎溪？

**Comment by LiuZhipeng99** [comment]
> > 这个下载地址是在外网？
> 
> 并不，是内网并且在测试中断网条件下尝试成功。

路由器一直开着就行？每次断电或者晚上断网后都要再用setup.sh？

**Comment by weearc** [comment]
> 路由器一直开着就行？每次断电或者晚上断网后都要再用setup.sh？

对，可以一直开着，如果出现未登录情况请时候ssh工具登录并运行命令：
```sh
(drcom > /dev/null &)&
```
一般情况下不会出现掉线的情况
