### ISSUE TITLE
虎溪校区服务器地址更新(需要更新setup.sh中虎溪校区的Base64配置)

### ISSUE THREAD

**Issue by wangxingran222** [purefkh/CQU_drcom#40]
昨天在openwrt上安装后没有效果，手动执行
```
exec micropython /usr/lib/micropython-drcom/latest-wired-micropython.py "$@"
```
发现执行到challenge函数的时候一直刷屏
![))UGHU4GV6PX8SHF4Y9E69N](https://user-images.githubusercontent.com/72983099/233674629-773ebad4-6000-4bf0-b564-730cd76381ee.png)
到[drcom-generic](https://github.com/drcoms/drcom-generic)那边看了一下，发现郭佬更新了虎溪校区的配置
![image](https://user-images.githubusercontent.com/72983099/233674976-571e1135-f19a-4635-96b7-752bfe875b52.png)
手动更新配置后，脚本正常工作。

更新后，setup.sh内虎溪校区的Base64配置为
```
c2VydmVyID0gIjEwLjEwLjguMTYyIgp1c2VybmFtZT0nJwpwYXNzd29yZD0nJwpob3N0X25hbWUgPSAiR0lMSUdJTElFWUUiCmhvc3Rfb3MgPSAiTk9URTciCmhvc3RfaXAgPSAiMTAuMjMwLjU5LjI1MSIKUFJJTUFSWV9ETlMgPSAiMjAyLjIwMi4wLjMzIgpkaGNwX3NlcnZlciA9ICIxMC4yMzAuNTkuMiIKbWFjID0gMHhiODg4ZTMwNTE2ODAKQ09OVFJPTENIRUNLU1RBVFVTID0gJ1x4MjAnCkFEQVBURVJOVU0gPSAnXHgwMicKS0VFUF9BTElWRV9WRVJTSU9OID0gJ1x4ZGNceDAyJwonJycKQVVUSF9WRVJTSU9OOgogICAgdW5zaWduZWQgY2hhciBDbGllbnRWZXJJbmZvQW5kSW50ZXJuZXRNb2RlOwogICAgdW5zaWduZWQgY2hhciBEb2dWZXJzaW9uOwonJycKQVVUSF9WRVJTSU9OID0gJ1x4MzFceDAwJwpJUERPRyA9ICdceDAxJwpyb3JfdmVyc2lvbiA9IEZhbHNlCg==
```

**Comment by Hagb** [comment]
感谢反馈！如果方便的话，欢迎提交PR。

**Comment by weearc** [comment]
Updated [7f43a5a](https://github.com/CQU-drcom/CQU_drcom/commit/7f43a5a5700b5479b9a8df4e325d0f45a36a4295)
